# This is a JSON Schema in YAML format.

$schema: http://json-schema.org/draft-07/schema
title: HMC credentials schema
description: JSON schema for the Z HMC Prometheus Exporter config file
type: object
required: []
additionalProperties: false
properties:
  version:
    description: "Version of the config file format"
    type: integer
  hmcs:
    description: The set of redundant HMCs
    type: array
    default: []
    items:
      type: object
      required:
        - host
        - userid
        - password
      additionalProperties: false
      properties:
        host:
          description: "Hostname or IP address of HMC"
          type: string
        userid:
          description: "Userid used by the exporter to log on to the HMC"
          type: string
        password:
          description: "Password of the HCM userid"
          type: string
        verify_cert:
          description: "Controls whether and how the HMC certificate is verified. For details, see doc section 'HMC certificate'"
          type: [boolean, string]
  metrics:
    description: "Deprecated: The HMC host and credentials"
    type: object
    required:
      - hmc
      - userid
      - password
    additionalProperties: false
    properties:
      hmc:
        description: "Deprecated: Hostname or IP address of HMC"
        type: string
      userid:
        description: "Deprecated: Userid used by the exporter to log on to the HMC"
        type: string
      password:
        description: "Deprecated: Password of the HCM userid"
        type: string
      verify_cert:
        description: "Deprecated: Controls whether and how the HMC certificate is verified. For details, see doc section 'HMC certificate'"
        type: [boolean, string]
  prometheus:
    description: Communication with Prometheus
    type: object
    additionalProperties: false
    properties:
      port:
        description: "Port for exporting."
        type: integer
      server_cert_file:
        description: "Path name of server certificate file. Enables the use of HTTPS."
        type: string
      server_key_file:
        description: "Path name of private key file."
        type: string
      ca_cert_file:
        description: "Path name of CA certificates file for validating the client certificate. Enables mutual TLS by requiring a client certificate to be presented."
        type: string
  extra_labels:
    description: "Additional Prometheus labels to be added to all metrics"
    type: array
    default: []
    items:
      type: object
      required:
        - name
        - value
      additionalProperties: false
      properties:
        name:
          description: "Label name"
          type: string
        value:
          description: "Label value, as a Jinja2 expression using certain variables"
          type: string
  metric_groups:
    description: Export control for the HMC and resource metric groups
    type: object
    additionalProperties: false
    patternProperties:
      "^[a-z0-9\\-]+$":
        description: "Key: Name of the HMC or resource metric group"
        type: object
        required:
          - export
        additionalProperties: false
        properties:
          export:
            description: "Indicates whether the metric group should be exported to Prometheus"
            type: boolean
