language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
  - pip install -r dev-requirements.txt
script:
  - py.test test/test.py --cov zhmc_prometheus_exporter.zhmc_prometheus_exporter --cov-report=html

  - flake8
after_success:
  - coveralls
