language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
  - pip install -r dev-requirements.txt
script:
  - python test/test.py --cov coveralls
  - flake8
after_success:
  - coveralls
