# Prometheus config file for the demo setup

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'zhmc'
    scrape_interval: 15s
    scrape_timeout: 15s
    scheme: http
    static_configs:
    - targets: ['localhost:9291']  # Host:port of the Z HMC Exporter
